apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: default
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # Block automatic K8s API token injection inside containers
      automountServiceAccountToken: false

      # Pod Security Context
      securityContext:
        seccompProfile:
          type: RuntimeDefault   # Restricts host kernel syscalls
        runAsNonRoot: true
        runAsUser: 1000

      containers:
        - name: frontend
          image: beatricebalzarini/fcc-frontend:v1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

          # Container Security Hardening
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5